pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push') {
            steps {
                sh 'docker build -t dhruv52991/hello-dhruv-app:${BUILD_NUMBER} ./app'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                    sh 'docker push dhruv52991/hello-dhruv-app:${BUILD_NUMBER}'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl --kubeconfig=/var/jenkins_home/.kube/config set image deployment/hello-dhruv-deployment hello-dhruv-container=dhruv52991/hello-dhruv-app:${BUILD_NUMBER} --record'
                sh 'kubectl --kubeconfig=/var/jenkins_home/.kube/config rollout status deployment/hello-dhruv-deployment'
            }
        }
    }
}


